import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dir = dirname(fileURLToPath(import.meta.url))
const dataPath = join(__dir, '../src/data/parades.json')

// city → region, keyed by country code
// Country language used; exceptions for well-known regions.
// Countries too small for meaningful subnational regions: LU, MT, IS, GG, CY
const REGIONS = {
  AT: {
    'Bad Ischl':            'Oberösterreich',
    'Bregenz':              'Vorarlberg',
    'Deutschlandsberg':     'Steiermark',
    'Graz':                 'Steiermark',
    'Innsbruck':            'Tirol',
    'Klagenfurt':           'Kärnten',
    'Kufstein':             'Tirol',
    'Linz':                 'Oberösterreich',
    'Mistelbach':           'Niederösterreich',
    'Mittersill':           'Salzburg',
    'Neustift im Stubaital':'Tirol',
    'Salzburg':             'Salzburg',
    'Spittal an der Drau':  'Kärnten',
    'St. Johann im Pongau': 'Salzburg',
    'St. Pölten':           'Niederösterreich',
    'Steyr':                'Oberösterreich',
    'Unken':                'Salzburg',
    'Villach':              'Kärnten',
    'Wien':                 'Wien',
  },
  BE: {
    'Antwerpen': 'Vlaanderen',
    'Brüssel':   'Bruxelles-Capitale',
    'Namur':     'Wallonie',
    'Sankt Vith':'Wallonie',
  },
  CH: {
    'Basel':    'Basel-Stadt',
    'Bern':     'Bern',
    'Lausanne': 'Vaud',
    'Lugano':   'Ticino',
    'Zürich':   'Zürich',
  },
  CZ: {
    'Brno': 'Jihomoravský kraj',
    'Prag': 'Praha',
  },
  DE: {
    // Baden-Württemberg
    'Albstadt':              'Baden-Württemberg',
    'Bad Mergentheim':       'Baden-Württemberg',
    'Biberach an der Riß':   'Baden-Württemberg',
    'Emmendingen':           'Baden-Württemberg',
    'Eppelheim':             'Baden-Württemberg',
    'Esslingen am Neckar':   'Baden-Württemberg',
    'Freiburg im Breisgau':  'Baden-Württemberg',
    'Friedrichshafen':       'Baden-Württemberg',
    'Heidelberg':            'Baden-Württemberg',
    'Heilbronn':             'Baden-Württemberg',
    'Herrenberg':            'Baden-Württemberg',
    'Karlsruhe':             'Baden-Württemberg',
    'Lahr/Schwarzwald':      'Baden-Württemberg',
    'Mannheim':              'Baden-Württemberg',
    'Mosbach':               'Baden-Württemberg',
    'Nürtingen':             'Baden-Württemberg',
    'Offenburg':             'Baden-Württemberg',
    'Pforzheim':             'Baden-Württemberg',
    'Rastatt':               'Baden-Württemberg',
    'Ravensburg':            'Baden-Württemberg',
    'Reutlingen':            'Baden-Württemberg',
    'Schorndorf':            'Baden-Württemberg',
    'Schwäbisch Hall':       'Baden-Württemberg',
    'Stuttgart':             'Baden-Württemberg',
    'Tübingen':              'Baden-Württemberg',
    'Ulm':                   'Baden-Württemberg',
    'Waldshut-Tiengen':      'Baden-Württemberg',
    'Überlingen':            'Baden-Württemberg',
    // Bayern
    'Amberg':                'Bayern',
    'Aschaffenburg':         'Bayern',
    'Augsburg':              'Bayern',
    'Bamberg':               'Bayern',
    'Bayreuth':              'Bayern',
    'Berchtesgaden':         'Bayern',
    'Coburg':                'Bayern',
    'Ebersberg':             'Bayern',
    'Eggenfelden':           'Bayern',
    'Erlangen':              'Bayern',
    'Fürth':                 'Bayern',
    'Herzogenaurach':        'Bayern',
    'Hof (Saale)':           'Bayern',
    'Ingolstadt':            'Bayern',
    'Karlsfeld':             'Bayern',
    'Kaufbeuren':            'Bayern',
    'Kelheim':               'Bayern',
    'Landsberg am Lech':     'Bayern',
    'Landshut':              'Bayern',
    'Memmingen':             'Bayern',
    'Michelstadt':           'Hessen',
    'Miltenberg':            'Bayern',
    'Mühldorf am Inn':       'Bayern',
    'München':               'Bayern',
    'Murnau am Staffelsee':  'Bayern',
    'Nürnberg':              'Bayern',
    'Pfaffenhofen an der Ilm':'Bayern',
    'Regen':                 'Bayern',
    'Regensburg':            'Bayern',
    'Rosenheim':             'Bayern',
    'Schongau':              'Bayern',
    'Schwabach':             'Bayern',
    'Schwandorf':            'Bayern',
    'Traunstein':            'Bayern',
    'Wasserburg am Inn':     'Bayern',
    'Weiden in der Oberpfalz':'Bayern',
    'Würmtal':               'Bayern',
    'Würzburg':              'Bayern',
    // Berlin
    'Berlin':                'Berlin',
    'Berlin-Marzahn':        'Berlin',
    'Berlin-Reinickendorf':  'Berlin',
    // Brandenburg
    'Angermünde':            'Brandenburg',
    'Bad Belzig':            'Brandenburg',
    'Bernau bei Berlin':     'Brandenburg',
    'Brandenburg an der Havel':'Brandenburg',
    'Cottbus':               'Brandenburg',
    'Eisenhüttenstadt':      'Brandenburg',
    'Frankfurt (Oder)':      'Brandenburg',
    'Golßen':                'Brandenburg',
    'Hennigsdorf':           'Brandenburg',
    'Jüterbog':              'Brandenburg',
    'Königs Wusterhausen':   'Brandenburg',
    'Luckenwalde':           'Brandenburg',
    'Ludwigsfelde':          'Brandenburg',
    'Müncheberg':            'Brandenburg',
    'Neuruppin':             'Brandenburg',
    'Oranienburg':           'Brandenburg',
    'Potsdam':               'Brandenburg',
    'Prenzlau':              'Brandenburg',
    'Eberswalde':            'Brandenburg',
    'Rathenow':              'Brandenburg',
    'Rheinsberg':            'Brandenburg',
    'Schwedt/Oder':          'Brandenburg',
    'Storkow (Mark)':        'Brandenburg',
    // Bremen
    'Bremen':                'Bremen',
    'Bremerhaven':           'Bremen',
    // Hamburg
    'Hamburg':               'Hamburg',
    // Hessen
    'Bad Kreuznach':         'Rheinland-Pfalz',
    'Bensheim':              'Hessen',
    'Darmstadt':             'Hessen',
    'Eschwege':              'Hessen',
    'Frankenberg (Eder)':    'Hessen',
    'Frankfurt am Main':     'Hessen',
    'Friedberg':             'Hessen',
    'Fritzlar':              'Hessen',
    'Fulda':                 'Hessen',
    'Gießen':                'Hessen',
    'Groß-Gerau':            'Hessen',
    'Hanau':                 'Hessen',
    'Hofheim am Taunus':     'Hessen',
    'Kassel':                'Hessen',
    'Limburg an der Lahn':   'Hessen',
    'Marburg':               'Hessen',
    'Wetzlar':               'Hessen',
    'Wiesbaden':             'Hessen',
    'Witzenhausen':          'Hessen',
    // Mecklenburg-Vorpommern
    'Greifswald':            'Mecklenburg-Vorpommern',
    'Neubrandenburg':        'Mecklenburg-Vorpommern',
    'Neustrelitz':           'Mecklenburg-Vorpommern',
    'Parchim':               'Mecklenburg-Vorpommern',
    'Rostock':               'Mecklenburg-Vorpommern',
    'Schwerin':              'Mecklenburg-Vorpommern',
    'Waren (Müritz)':        'Mecklenburg-Vorpommern',
    // Niedersachsen
    'Aurich':                'Niedersachsen',
    'Bramsche':              'Niedersachsen',
    'Braunschweig':          'Niedersachsen',
    'Buchholz in der Nordheide':'Niedersachsen',
    'Burgdorf':              'Niedersachsen',
    'Celle':                 'Niedersachsen',
    'Delmenhorst':           'Niedersachsen',
    'Emden':                 'Niedersachsen',
    'Gifhorn':               'Niedersachsen',
    'Goslar':                'Niedersachsen',
    'Göttingen':             'Niedersachsen',
    'Hameln':                'Niedersachsen',
    'Hannover':              'Niedersachsen',
    'Herzberg am Harz':      'Niedersachsen',
    'Hildesheim':            'Niedersachsen',
    'Leer':                  'Niedersachsen',
    'Lüchow':                'Niedersachsen',
    'Lüneburg':              'Niedersachsen',
    'Norden':                'Niedersachsen',
    'Nordenham':             'Niedersachsen',
    'Northeim':              'Niedersachsen',
    'Oldenburg':             'Niedersachsen',
    'Osnabrück':             'Niedersachsen',
    'Papenburg':             'Niedersachsen',
    'Peine':                 'Niedersachsen',
    'Ronnenberg':            'Niedersachsen',
    'Rotenburg (Wümme)':     'Niedersachsen',
    'Stade':                 'Niedersachsen',
    'Vechta':                'Niedersachsen',
    'Walsrode':              'Niedersachsen',
    'Winsen (Luhe)':         'Niedersachsen',
    // Nordrhein-Westfalen
    'Aachen':                'Nordrhein-Westfalen',
    'Alfter':                'Nordrhein-Westfalen',
    'Arnsberg':              'Nordrhein-Westfalen',
    'Bielefeld':             'Nordrhein-Westfalen',
    'Bocholt':               'Nordrhein-Westfalen',
    'Bochum':                'Nordrhein-Westfalen',
    'Bonn':                  'Nordrhein-Westfalen',
    'Brühl':                 'Nordrhein-Westfalen',
    'Detmold':               'Nordrhein-Westfalen',
    'Dortmund':              'Nordrhein-Westfalen',
    'Duisburg':              'Nordrhein-Westfalen',
    'Düren':                 'Nordrhein-Westfalen',
    'Düsseldorf':            'Nordrhein-Westfalen',
    'Erkrath':               'Nordrhein-Westfalen',
    'Essen':                 'Nordrhein-Westfalen',
    'Euskirchen':            'Nordrhein-Westfalen',
    'Geilenkirchen':         'Nordrhein-Westfalen',
    'Gelsenkirchen':         'Nordrhein-Westfalen',
    'Gummersbach':           'Nordrhein-Westfalen',
    'Gütersloh':             'Nordrhein-Westfalen',
    'Haltern am See':        'Nordrhein-Westfalen',
    'Hattingen':             'Nordrhein-Westfalen',
    'Herne':                 'Nordrhein-Westfalen',
    'Jülich':                'Nordrhein-Westfalen',
    'Krefeld':               'Nordrhein-Westfalen',
    'Köln':                  'Nordrhein-Westfalen',
    'Leverkusen':            'Nordrhein-Westfalen',
    'Lüdenscheid':           'Nordrhein-Westfalen',
    'Minden':                'Nordrhein-Westfalen',
    'Moers':                 'Nordrhein-Westfalen',
    'Mönchengladbach':       'Nordrhein-Westfalen',
    'Mülheim an der Ruhr':   'Nordrhein-Westfalen',
    'Münster':               'Nordrhein-Westfalen',
    'Nettetal':              'Nordrhein-Westfalen',
    'Oberhausen':            'Nordrhein-Westfalen',
    'Olpe':                  'Nordrhein-Westfalen',
    'Paderborn':             'Nordrhein-Westfalen',
    'Ratingen':              'Nordrhein-Westfalen',
    'Recklinghausen':        'Nordrhein-Westfalen',
    'Remscheid':             'Nordrhein-Westfalen',
    'Rheine':                'Nordrhein-Westfalen',
    'Siegburg':              'Nordrhein-Westfalen',
    'Siegen':                'Nordrhein-Westfalen',
    'Soest':                 'Nordrhein-Westfalen',
    'Solingen':              'Nordrhein-Westfalen',
    'Viersen':               'Nordrhein-Westfalen',
    'Warendorf':             'Nordrhein-Westfalen',
    'Wegberg':               'Nordrhein-Westfalen',
    'Wesel':                 'Nordrhein-Westfalen',
    'Wuppertal':             'Nordrhein-Westfalen',
    // Rheinland-Pfalz
    'Bingen am Rhein':       'Rheinland-Pfalz',
    'Kaiserslautern':        'Rheinland-Pfalz',
    'Koblenz':               'Rheinland-Pfalz',
    'Mainz':                 'Rheinland-Pfalz',
    'Trier':                 'Rheinland-Pfalz',
    // Saarland
    'Saarbrücken':           'Saarland',
    // Sachsen
    'Chemnitz':              'Sachsen',
    'Döbeln':                'Sachsen',
    'Dresden':               'Sachsen',
    'Freiberg':              'Sachsen',
    'Görlitz':               'Sachsen',
    'Leipzig':               'Sachsen',
    'Pirna':                 'Sachsen',
    'Plauen':                'Sachsen',
    'Riesa':                 'Sachsen',
    'Stollberg':             'Sachsen',
    'Torgau':                'Sachsen',
    'Zittau':                'Sachsen',
    'Zwickau':               'Sachsen',
    // Sachsen-Anhalt
    'Dessau-Rosslau':        'Sachsen-Anhalt',
    'Halle (Saale)':         'Sachsen-Anhalt',
    'Köthen':                'Sachsen-Anhalt',
    'Lutherstadt Wittenberg':'Sachsen-Anhalt',
    'Magdeburg':             'Sachsen-Anhalt',
    'Merseburg':             'Sachsen-Anhalt',
    'Naumburg (Saale)':      'Sachsen-Anhalt',
    'Sangerhausen':          'Sachsen-Anhalt',
    'Schönebeck':            'Sachsen-Anhalt',
    'Stendal':               'Sachsen-Anhalt',
    'Wernigerode':           'Sachsen-Anhalt',
    // Schleswig-Holstein
    'Ahrensburg':            'Schleswig-Holstein',
    'Bad Oldesloe':          'Schleswig-Holstein',
    'Bad Segeberg':          'Schleswig-Holstein',
    'Elmshorn':              'Schleswig-Holstein',
    'Flensburg':             'Schleswig-Holstein',
    'Heide':                 'Schleswig-Holstein',
    'Hohenlockstedt':        'Schleswig-Holstein',
    'Husum':                 'Schleswig-Holstein',
    'Kiel':                  'Schleswig-Holstein',
    'Lübeck':                'Schleswig-Holstein',
    'Meldorf':               'Schleswig-Holstein',
    'Mölln':                 'Schleswig-Holstein',
    'Neumünster':            'Schleswig-Holstein',
    'Norderstedt':           'Schleswig-Holstein',
    'Pinneberg':             'Schleswig-Holstein',
    'Quickborn':             'Schleswig-Holstein',
    'Rendsburg':             'Schleswig-Holstein',
    'Schleswig':             'Schleswig-Holstein',
    'Wacken':                'Schleswig-Holstein',
    // Thüringen
    'Erfurt':                'Thüringen',
    'Gotha':                 'Thüringen',
    'Ilmenau':               'Thüringen',
    'Jena':                  'Thüringen',
    'Mühlhausen/Thüringen':  'Thüringen',
    'Neustadt an der Orla':  'Thüringen',
    'Nordhausen':            'Thüringen',
    'Weimar':                'Thüringen',
  },
  DK: {
    'Aalborg':    'Nordjylland',
    'Aarhus':     'Midtjylland',
    'Kopenhagen': 'Hovedstaden',
    'Tórshavn':   'Færøerne',
  },
  EE: { 'Tallinn': 'Harju maakond' },
  ES: {
    'Alicante':                   'Comunitat Valenciana',
    'Barcelona':                  'Catalunya',
    'Benidorm':                   'Comunitat Valenciana',
    'Bilbao':                     'País Vasco',
    'Cartagena':                  'Región de Murcia',
    'Córdoba':                    'Andalucía',
    'Gijón':                      'Principado de Asturias',
    'Ibiza-Stadt':                'Illes Balears',
    'Las Palmas de Gran Canaria': 'Canarias',
    'Madrid':                     'Comunidad de Madrid',
    'Maspalomas':                 'Canarias',
    'Murcia':                     'Región de Murcia',
    'Málaga':                     'Andalucía',
    'Palma de Mallorca':          'Illes Balears',
    'Santa Cruz de Tenerife':     'Canarias',
    'Sevilla':                    'Andalucía',
    'Sitges':                     'Catalunya',
    'Tarragona':                  'Catalunya',
    'Torremolinos':               'Andalucía',
    'Valencia':                   'Comunitat Valenciana',
    'Zaragoza':                   'Aragón',
  },
  FI: {
    'Helsinki': 'Uusimaa',
    'Joensuu':  'Pohjois-Karjala',
    'Lahti':    'Päijät-Häme',
    'Tampere':  'Pirkanmaa',
  },
  FR: {
    // Auvergne-Rhône-Alpes
    'Annecy':              'Auvergne-Rhône-Alpes',
    'Bourg-en-Bresse':     'Auvergne-Rhône-Alpes',
    'Bourgoin-Jallieu':    'Auvergne-Rhône-Alpes',
    'Chambéry':            'Auvergne-Rhône-Alpes',
    'Clermont-Ferrand':    'Auvergne-Rhône-Alpes',
    'Grenoble':            'Auvergne-Rhône-Alpes',
    "L'Arbresle":          'Auvergne-Rhône-Alpes',
    'Lyon':                'Auvergne-Rhône-Alpes',
    'Roanne':              'Auvergne-Rhône-Alpes',
    'Saint-Jean-de-Maurienne': 'Auvergne-Rhône-Alpes',
    'Saint-Martin-en-Haut':'Auvergne-Rhône-Alpes',
    'Sallanches':          'Auvergne-Rhône-Alpes',
    'Valence':             'Auvergne-Rhône-Alpes',
    // Bourgogne-Franche-Comté
    'Auxerre':             'Bourgogne-Franche-Comté',
    'Avallon':             'Bourgogne-Franche-Comté',
    'Belfort':             'Bourgogne-Franche-Comté',
    'Besançon':            'Bourgogne-Franche-Comté',
    'Cluny':               'Bourgogne-Franche-Comté',
    'Dijon':               'Bourgogne-Franche-Comté',
    'Lons-le-Saunier':     'Bourgogne-Franche-Comté',
    'Nevers':              'Bourgogne-Franche-Comté',
    'Vesoul':              'Bourgogne-Franche-Comté',
    // Bretagne
    'Brest':               'Bretagne',
    'Douarnenez':          'Bretagne',
    'Fougères':            'Bretagne',
    'Lorient':             'Bretagne',
    'Pontrieux':           'Bretagne',
    'Quimper':             'Bretagne',
    'Rennes':              'Bretagne',
    'Saint-Brieuc':        'Bretagne',
    'Vannes':              'Bretagne',
    // Centre-Val de Loire
    'Blois':               'Centre-Val de Loire',
    'Bourges':             'Centre-Val de Loire',
    'Chartres':            'Centre-Val de Loire',
    'Orléans':             'Centre-Val de Loire',
    'Tours':               'Centre-Val de Loire',
    // Grand Est
    'Metz':                'Grand Est',
    'Mulhouse':            'Grand Est',
    'Nancy':               'Grand Est',
    'Reims':               'Grand Est',
    'Straßburg':           'Grand Est',
    'Thionville':          'Grand Est',
    // Hauts-de-France
    'Amiens':              'Hauts-de-France',
    'Arras':               'Hauts-de-France',
    'Calais':              'Hauts-de-France',
    'Compiègne':           'Hauts-de-France',
    'Douai':               'Hauts-de-France',
    'Lens':                'Hauts-de-France',
    'Lille':               'Hauts-de-France',
    'Roubaix':             'Hauts-de-France',
    'Saint-Quentin':       'Hauts-de-France',
    'Tourcoing':           'Hauts-de-France',
    // Île-de-France
    'Paris':               'Île-de-France',
    // Normandie
    'Alençon':             'Normandie',
    'Caen':                'Normandie',
    'Lisieux':             'Normandie',
    'Rouen':               'Normandie',
    // Nouvelle-Aquitaine
    'Agen':                'Nouvelle-Aquitaine',
    'Angoulême':           'Nouvelle-Aquitaine',
    'Biarritz':            'Nouvelle-Aquitaine',
    'Bordeaux':            'Nouvelle-Aquitaine',
    'Chenevelles':         'Nouvelle-Aquitaine',
    'Guéret':              'Nouvelle-Aquitaine',
    'La Rochelle':         'Nouvelle-Aquitaine',
    'Libourne':            'Nouvelle-Aquitaine',
    'Niort':               'Nouvelle-Aquitaine',
    'Périgueux':           'Nouvelle-Aquitaine',
    'Poitiers':            'Nouvelle-Aquitaine',
    'Saintes':             'Nouvelle-Aquitaine',
    'Saint-Paul-lès-Dax':  'Nouvelle-Aquitaine',
    // Occitanie
    'Alès':                'Occitanie',
    'Béziers':             'Occitanie',
    'Carcassonne':         'Occitanie',
    'Montauban':           'Occitanie',
    'Montpellier':         'Occitanie',
    'Narbonne':            'Occitanie',
    'Nîmes':               'Occitanie',
    'Perpignan':           'Occitanie',
    'Rodez':               'Occitanie',
    'Saint-Gaudens':       'Occitanie',
    'Tarbes':              'Occitanie',
    'Toulouse':            'Occitanie',
    // Pays de la Loire
    'Angers':              'Pays de la Loire',
    'Clisson':             'Pays de la Loire',
    'La Roche-sur-Yon':    'Pays de la Loire',
    'Laval':               'Pays de la Loire',
    'Le Mans':             'Pays de la Loire',
    'Nantes':              'Pays de la Loire',
    'Saint-Nazaire':       'Pays de la Loire',
    // Provence-Alpes-Côte d'Azur
    'Aix-en-Provence':     "Provence-Alpes-Côte d'Azur",
    'Arles':               "Provence-Alpes-Côte d'Azur",
    'Avignon':             "Provence-Alpes-Côte d'Azur",
    'La Ciotat':           "Provence-Alpes-Côte d'Azur",
    'Marseille':           "Provence-Alpes-Côte d'Azur",
    'Molines-en-Queyras':  "Provence-Alpes-Côte d'Azur",
    'Nizza':               "Provence-Alpes-Côte d'Azur",
    'Toulon':              "Provence-Alpes-Côte d'Azur",
  },
  GB: {
    // England — traditional counties
    'Bath':                'Somerset',
    'Birmingham':          'West Midlands',
    'Blackpool':           'Lancashire',
    'Bourne':              'Lincolnshire',
    'Bradford':            'West Yorkshire',
    'Brighton':            'East Sussex',
    'Bristol':             'Bristol',
    'Bury':                'Greater Manchester',
    'Canterbury':          'Kent',
    'Chelmsford':          'Essex',
    'Chester':             'Cheshire',
    'Chesterfield':        'Derbyshire',
    'Congleton':           'Cheshire',
    'Coventry':            'West Midlands',
    'Croydon':             'Greater London',
    'Derby':               'Derbyshire',
    'Doncaster':           'South Yorkshire',
    'Durham':              'County Durham',
    'Eastbourne':          'East Sussex',
    'Eastleigh':           'Hampshire',
    'Ely':                 'Cambridgeshire',
    'Exeter':              'Devon',
    'Exmouth':             'Devon',
    'Folkestone':          'Kent',
    'Gloucester':          'Gloucestershire',
    'Great Malvern':       'Worcestershire',
    'Hebden Bridge':       'West Yorkshire',
    'Hertford':            'Hertfordshire',
    'Hull':                'East Yorkshire',
    'Lancaster':           'Lancashire',
    'Leeds':               'West Yorkshire',
    'Leicester':           'Leicestershire',
    'Lincoln':             'Lincolnshire',
    'Liverpool':           'Merseyside',
    'London':              'Greater London',
    'Macclesfield':        'Cheshire',
    'Manchester':          'Greater Manchester',
    'Margate':             'Kent',
    'Newcastle upon Tyne': 'Tyne and Wear',
    'Newquay':             'Cornwall',
    'Northampton':         'Northamptonshire',
    'Norwich':             'Norfolk',
    'Nottingham':          'Nottinghamshire',
    'Oxford':              'Oxfordshire',
    'Plymouth':            'Devon',
    'Portsmouth':          'Hampshire',
    'Reading':             'Berkshire',
    'Royal Leamington Spa':'Warwickshire',
    'Ryde':                'Isle of Wight',
    'Salford':             'Greater Manchester',
    'Saltash':             'Cornwall',
    'Sheffield':           'South Yorkshire',
    'Silloth':             'Cumbria',
    'Southampton':         'Hampshire',
    'Stockport':           'Greater Manchester',
    'Stoke-on-Trent':      'Staffordshire',
    'Swindon':             'Wiltshire',
    'Torquay':             'Devon',
    'Wakefield':           'West Yorkshire',
    'Walsall':             'West Midlands',
    'Witney':              'Oxfordshire',
    'Wolverhampton':       'West Midlands',
    'Worthing':            'West Sussex',
    'York':                'North Yorkshire',
    // Scotland
    'Edinburgh':           'Scotland',
    'Glasgow':             'Scotland',
    'Kirkcaldy':           'Scotland',
    'Livingston':          'Scotland',
    'Shetland-Inseln':     'Scotland',
    // Wales
    'Cardiff':             'Wales',
    'Swansea':             'Wales',
    // Northern Ireland
    'Belfast':             'Northern Ireland',
    'Derry':               'Northern Ireland',
    'Newry':               'Northern Ireland',
  },
  GR: {
    'Athen':        'Attiki',
    'Thessaloniki': 'Kentriki Makedonia',
  },
  HR: {
    'Split':  'Splitsko-dalmatinska',
    'Zagreb': 'Zagrebačka',
  },
  IE: {
    'Castlebar': 'Connacht',
    'Cork':      'Munster',
    'Drogheda':  'Leinster',
    'Dublin':    'Leinster',
    'Limerick':  'Munster',
  },
  IT: {
    // Abruzzo
    'Giulianova':          'Abruzzo',
    // Calabria
    'Castrovillari':       'Calabria',
    // Campania
    'Atripalda':           'Campania',
    'Neapel':              'Campania',
    'Nocera Inferiore':    'Campania',
    'Pompeji':             'Campania',
    'Portici':             'Campania',
    'Salerno':             'Campania',
    // Emilia-Romagna
    'Bologna':             'Emilia-Romagna',
    'Comacchio':           'Emilia-Romagna',
    'Forlì':               'Emilia-Romagna',
    'Modena':              'Emilia-Romagna',
    'Parma':               'Emilia-Romagna',
    'Rimini':              'Emilia-Romagna',
    // Friuli-Venezia Giulia
    'Udine':               'Friuli-Venezia Giulia',
    // Lazio
    'Civitavecchia':       'Lazio',
    'Monterotondo':        'Lazio',
    'Rom':                 'Lazio',
    'Viterbo':             'Lazio',
    // Liguria
    'Genua':               'Liguria',
    'La Spezia':           'Liguria',
    'Sanremo':             'Liguria',
    'Savona':              'Liguria',
    // Lombardia
    'Bergamo':             'Lombardia',
    'Brescia':             'Lombardia',
    'Cologno Monzese / Brugherio': 'Lombardia',
    'Cremona':             'Lombardia',
    'Lecco':               'Lombardia',
    'Lodi':                'Lombardia',
    'Mailand':             'Lombardia',
    'Pavia':               'Lombardia',
    'Varese':              'Lombardia',
    // Marche
    'Ancona':              'Marche',
    // Molise
    'Campobasso':          'Molise',
    // Piemonte
    'Alessandria':         'Piemonte',
    'Asti':                'Piemonte',
    'Cuneo':               'Piemonte',
    'Ostana':              'Piemonte',
    'Turin':               'Piemonte',
    'Vercelli':            'Piemonte',
    // Puglia
    'Bari':                'Puglia',
    'Gallipoli':           'Puglia',
    'Lecce':               'Puglia',
    'Ostuni':              'Puglia',
    'Palagianello':        'Puglia',
    'San Marzano di San Giuseppe': 'Puglia',
    'Taranto':             'Puglia',
    'Villa Castelli':      'Puglia',
    // Sardegna
    'Cagliari':            'Sardegna',
    // Sicilia
    'Caltagirone':         'Sicilia',
    'Cammarata':           'Sicilia',
    'Catania':             'Sicilia',
    'Enna':                'Sicilia',
    'Favignana':           'Sicilia',
    'Lipari':              'Sicilia',
    'Messina':             'Sicilia',
    'Palermo':             'Sicilia',
    'Ragusa':              'Sicilia',
    'Syrakus':             'Sicilia',
    // Toscana
    'Grosseto':            'Toscana',
    // Trentino-Alto Adige
    'Arco':                'Trentino-Alto Adige',
    // Umbria
    'Perugia':             'Umbria',
    // Valle d'Aosta
    'Aosta':               "Valle d'Aosta",
    // Veneto
    'Belluno':             'Veneto',
    'Dolo':                'Veneto',
    'Padova':              'Veneto',
    'Rovigo':              'Veneto',
    'Treviso':             'Veneto',
    'Verona':              'Veneto',
    'Vicenza':             'Veneto',
  },
  LT: { 'Vilnius': 'Vilniaus apskritis' },
  LV: { 'Riga':    'Rīgas reģions' },
  NL: {
    'Alkmaar':   'Noord-Holland',
    'Amsterdam': 'Noord-Holland',
    'Gouda':     'Zuid-Holland',
    'Maastricht':'Limburg',
    'Rotterdam': 'Zuid-Holland',
    'Tilburg':   'Noord-Brabant',
    'Utrecht':   'Utrecht',
  },
  NO: {
    'Bergen':       'Vestland',
    'Kristiansand': 'Agder',
    'Oslo':         'Oslo',
  },
  PL: {
    'Danzig':   'Pomorskie',
    'Katowice': 'Śląskie',
    'Krakau':   'Małopolskie',
    'Poznań':   'Wielkopolskie',
    'Warschau': 'Mazowieckie',
    'Wrocław':  'Dolnośląskie',
  },
  PT: {
    'Coimbra':  'Centro',
    'Lissabon': 'Lisboa',
  },
  RO: {
    'Brașov':  'Brașov',
    'Bukarest':'Ilfov',
  },
  RS: { 'Belgrad': 'Beograd' },
  SE: {
    'Boden':       'Norrbotten',
    'Borås':       'Västra Götaland',
    'Eskilstuna':  'Södermanland',
    'Falun':       'Dalarna',
    'Gävle':       'Gävleborg',
    'Göteborg':    'Västra Götaland',
    'Katrineholm': 'Södermanland',
    'Kristianstad':'Skåne',
    'Lund':        'Skåne',
    'Malmö':       'Skåne',
    'Norrköping':  'Östergötland',
    'Norrtälje':   'Stockholm',
    'Stockholm':   'Stockholm',
    'Sundsvall':   'Västernorrland',
    'Söderhamn':   'Gävleborg',
    'Trollhättan': 'Västra Götaland',
    'Västerås':    'Västmanland',
    'Växjö':       'Kronoberg',
    'Östersund':   'Jämtland',
  },
  SI: { 'Ljubljana': 'Osrednjeslovenska' },
  SK: { 'Bratislava': 'Bratislavský kraj' },
  UA: { 'Kiew': 'Oblast Kiew' },
  // Single-city countries with meaningful subnational unit
  AL: { 'Tirana':    'Qarku i Tiranës' },
  BA: { 'Sarajevo':  'Kanton Sarajevo' },
  BG: { 'Sofia':     'Oblast Sofija-Grad' },
  HU: { 'Budapest':  'Budapest' },
  MD: { 'Chişinău':  'Municipiul Chișinău' },
  MK: { 'Skopje':    'Skopje' },
  // DE cities previously missed
  // Eberswalde → Brandenburg, Ratingen → NRW (added inline above)
}

const parades = JSON.parse(readFileSync(dataPath, 'utf8'))
let assigned = 0, missing = []

parades.forEach(p => {
  const region = REGIONS[p.country]?.[p.city] ?? ''
  p.region = region
  if (region) assigned++
  else missing.push(`${p.country}/${p.city}`)
})

writeFileSync(dataPath, JSON.stringify(parades, null, 2))
console.log(`Done. Assigned regions: ${assigned}/${parades.length}`)
if (missing.length) {
  console.log(`No region for ${missing.length} entries:`)
  missing.forEach(m => console.log('  ' + m))
}
